In [2]:
import numpy as np

In [7]:
#1 Using Python List :
py_lst=[1,2,3,4,"Hassan"]
arr=np.array(py_lst)
print(arr,arr.dtype,arr.shape,type(arr))

['1' '2' '3' '4' 'Hassan'] <U21 (5,) <class 'numpy.ndarray'>


In [6]:
# Directly :
arr2=np.array([1,2,3,4,"Hassan"])
print(arr2,arr2.dtype,arr2.shape,type(arr2))

['1' '2' '3' '4' 'Hassan'] <U21 (5,) <class 'numpy.ndarray'>


In [8]:
# 2-D Array :
two_d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_d,two_d.dtype,two_d.shape,type(two_d))

[[1 2 3]
 [4 5 6]
 [7 8 9]] int64 (3, 3) <class 'numpy.ndarray'>


In [12]:
# Zero Array :
z  = np.zeros((5,4),dtype="int64")
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
# One - Array :
o = np.ones((3,3))
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Custom Single Value :
hundred = np.full((5,2),100)
print(hundred)

[[100 100]
 [100 100]
 [100 100]
 [100 100]
 [100 100]]


In [15]:
# Identity Matrix L
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
# Range Values
a = np.arange(0,11,2)
print(a)

[ 0  2  4  6  8 10]


In [18]:
# Total Numbers ;
a = np.linspace(1,100,4)
print(a)

[  1.  34.  67. 100.]
