In [2]:
import numpy as np

In [11]:

ar = np.array([30,10,20,10,50.64,40])

# Aggregates :

print(ar)
print(np.min(ar))
print(np.max(ar))
print(np.argmin(ar))
print(np.argmax(ar))
print(np.sum(ar))
print(np.prod(ar))
print(np.mean(ar))
print(np.var(ar))
print(np.std(ar))

# Power :
print(np.square(ar))
print(ar ** 2)
print(np.sqrt(ar))
print(np.pow(ar , 3))


# Logarithm :
print(np.log(ar)) # Natural Log
print(np.log10(ar))
print(np.log2(ar))
print(np.exp(ar))

# Round :
print(np.round(ar))
print(np.ceil(ar))
print(np.floor(ar))
print(np.trunc(ar))

#Extra :
print(np.unique(ar))
print(np.abs(ar))
print(np.sort(ar))

[30.   10.   20.   10.   50.64 40.  ]
10.0
50.64
1
4
160.64
121536000.0
26.77333333333333
227.25688888888888
15.075041919971197
[ 900.      100.      400.      100.     2564.4096 1600.    ]
[ 900.      100.      400.      100.     2564.4096 1600.    ]
[5.47722558 3.16227766 4.47213595 3.16227766 7.11617875 6.32455532]
[ 27000.         1000.         8000.         1000.       129861.702144
  64000.      ]
[3.40119738 2.30258509 2.99573227 2.30258509 3.92474178 3.68887945]
[1.47712125 1.         1.30103    1.         1.7044937  1.60205999]
[4.9068906  3.32192809 4.32192809 3.32192809 5.6622055  5.32192809]
[1.06864746e+13 2.20264658e+04 4.85165195e+08 2.20264658e+04
 9.83269490e+21 2.35385267e+17]
[30. 10. 20. 10. 51. 40.]
[30. 10. 20. 10. 51. 40.]
[30. 10. 20. 10. 50. 40.]
[30. 10. 20. 10. 50. 40.]
[10.   20.   30.   40.   50.64]
[30.   10.   20.   10.   50.64 40.  ]
[10.   10.   20.   30.   40.   50.64]
