In [1]:
import numpy as np

In [6]:
# Sum of 2 - D Array :

ar = np.array([[1,2],[3,4]])

# Whole Sum :
print(np.sum(ar))

# Col - Sum :
print(np.sum(ar,axis = 0))

# Row - Sum :
print(np.sum(ar,axis = 1))

10
[4 6]
[3 7]


In [8]:
# Slicing :

"""
  0 1 2
0 4 5 6 
1 7 8 9
2 4 2 5
"""

ar=np.array([[4,5,6],[7,8,9],[4,2,5]])
print(ar)

new = ar[0:2,1:2]
print(new)

[[4 5 6]
 [7 8 9]
 [4 2 5]]
[[5]
 [8]]


In [11]:
ar2 = np.array([[1,2],[4,3]])
print(ar2)
print(ar2[0][1])
print(ar2[0,1])

[[1 2]
 [4 3]]
2
2


In [17]:
# 3D Array:

td = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(td,td.ndim,td.shape)

#Access :

print(td[1][1][0])
print(td[1,1,0])

#Slicing using axis ;

print(td[0:2,0:2,0:1])

# Modifying the sliced area with a particular value :

td[0:2,0:2,0:1] = 66
print(td)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 3 (2, 2, 2)
6
6
[[[0]
  [2]]

 [[4]
  [6]]]
[[[66  1]
  [66  3]]

 [[66  5]
  [66  7]]]
