In [1]:
import numpy as np

In [2]:
ar=np.array([[1,2,3],[4,5,6]])
print(ar,ar.shape)

#Reshaping :
reshaped = ar.reshape((3,2))
print(reshaped,reshaped.shape)

#Converting 2-D Into 1-D :
flat = reshaped.flatten()
print(flat,flat.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [3]:
# Normal Indexing :

print(flat[0])
flat[0]=10
print(flat[0])

1
10


In [4]:
# Fancy Indexng :

index = [0,2,3]
print(flat[index])

[10  3  4]


In [5]:
# Boolean Indexing :

print(flat[flat % 2 == 0])
print(flat[flat>5])

[10  2  4  6]
[10  6]


In [6]:
# Array Slicing L

flat=flat[1:4:2]
print(flat)

[2 4]


In [8]:
# View vs Copy :

#Python List :

lst = [10,20,30,40,50]
print(f"Orignal List : {lst}")

sub = lst [2 : 5]
print(f"SubList : {sub}")

sub[0] = "x"

print("After :")
print(f"Orignal List : {lst}")
print(f"SubList : {sub} ")



# Numpy Arrays :

arr = np.array(lst)

print(f"Orignal Array : {lst}")

subr = arr [2 : 5]
print(f"SubArray : {subr}")

subr[0] = 100000

print("After :")
print(f"Orignal List : {arr}")
print(f"SubArray : {subr} ")


Orignal List : [10, 20, 30, 40, 50]
SubList : [30, 40, 50]
After :
Orignal List : [10, 20, 30, 40, 50]
SubList : ['x', 40, 50] 
Orignal Array : [10, 20, 30, 40, 50]
SubArray : [30 40 50]
After :
Orignal List : [    10     20 100000     40     50]
SubArray : [100000     40     50] 
